---
title: "equations for all the ASL in the world"
output: word_document
---

## Stratified

### If abundance is known without error

#### If there are proportions

The proportion of each age, sex, and/or length category *z* will be estimated for each sampling stratum *t* as follows:

$$\hat{p}_{tz}=\frac{n_{tz}}{n_t}$$

in which $n_{tz}$ equals the number of fish sampled during sampling stratum $t$ classified as age, sex, and/or length category $z$, and $n_t$ equals the number of fish sampled for age, sex, and/or length determination within sampling stratum $t$.

The sampling variance of $\hat{p}_{tz}$ will be estimated as the following (Cochran 1977), in which $N_t$ represents the total abundance of fish in sampling stratum *t*:

$$\hat{var}[\hat{p}_{tz}]=\frac{\hat{p}_{tz}(1-\hat{p}_{tz})}{n_t-1}\left(\frac{N_t-n_t}{N_t-1}\right)$$

if the finite population correction factor (FPC) is used; otherwise, as the following:

$$\hat{var}[\hat{p}_{tz}]=\frac{\hat{p}_{tz}(1-\hat{p}_{tz})}{n_t-1}$$

The total abundance by age, sex, and/or length category in each sampling stratum will be estimated as follows:

$$\hat{N}_{tz}=N_t\hat{p}_{tz}$$

with variance estimated as

$$\hat{var}[\hat{N}_{tz}]=N_t^2\hat{var}[\hat{p}_{tz}]$$

The total abundance by age, sex, and/or length category and its variance will then be estimated by summation as follows:

$$\hat{N}_z=\sum_{t=1}^{L}\hat{N}_{tz}$$

and

$$\hat{var}[\hat{N}_{z}]=\sum_{t=1}^{L}\hat{var}[\hat{N}_{tz}]$$

where $L$ equals the number of sampling strata.

Finally, the overall proportion by age, sex, and/or length category and its variance will be estimated as follows:

$$\hat{p}_z=\frac{\hat{N}_z}{N}$$

and

$$\hat{var}[\hat{p}_z]=\frac{\hat{var}[\hat{N}_z]}{N^2}$$

where $N$ is the total abundance across all sampling periods.

The mean length by age, sex, and/or length for each sampling stratum will be estimated as follows:

$$\bar{x}_{tz}=\frac{\sum_{i=1}^{n_{tz}}x_{tzi}}{n_{tz}}$$

where $x_{tzi}$ is the length of the *i*th fish sampled of age, sex, and/or length $z$ during sampling stratum $t$.

The sampling variance of $\bar{x}_{tz}$ will be estimated as

$$\hat{var}[\bar{x}_{tz}]=\frac{\sum_{i=1}^{n_{tz}}(x_{tzi}-\bar{x}_{tz})^2}{n_{tz}(n_{tz}-1)}\left(\frac{\hat{N}_{tz}-n_{tz}}{\hat{N}_{tz}-1}\right)$$

if the finite population correction factor (FPC) will be used; otherwise, as the following:

$$\hat{var}[\bar{x}_{tz}]=\frac{\sum_{i=1}^{n_{tz}}(x_{tzi}-\bar{x}_{tz})^2}{n_{tz}(n_{tz}-1)}$$

The mean length by age, sex, and/or length category will then be estimated as follows:

$$\bar{x}_z=\sum_{t=1}^{L}\frac{\hat{N}_{tz}}{\hat{N}_z}\bar{x}_{tz}$$

with its variance approximated using a Taylor's series expansion (Mood et al. 1974):

$$\hat{var}[\bar{x}_z]\approx\sum_{t=1}^{L}\frac{\hat{N}_{tz}^2}{\hat{N}_z^2}\hat{var}[\bar{x}_{tz}]+\sum_{t=1}^{L}\frac{\left(\bar{x}_{tz}\hat{N}_z-\left(\sum_{u=1}^{L}\bar{x}_{uz}\hat{N}_{uz}\right)\right)^2}{\hat{N}_z^4}\hat{var}[\hat{N}_{tz}]$$

#### If there are no proportions to estimate

The mean length for each sampling stratum will be estimated as follows, where $x_{ti}$ is the length of the *i*th fish sampled within sampling stratum $t$, and $n_t$ is the number of fish in stratum *t* sampled for length:

$$\bar{x}_{t}=\frac{\sum_{i=1}^{n_{t}}x_{ti}}{n_{t}}$$

The sampling variance of $\bar{x}_{t}$ will be estimated as

$$\hat{var}[\bar{x}_{t}]=\frac{\sum_{i=1}^{n_{t}}(x_{ti}-\bar{x}_{t})^2}{n_{t}(n_{t}-1)}\left(\frac{N_{t}-n_{t}}{N_{t}-1}\right)$$

if abundance per stratum $N_t$ is known and if the finite population correction factor is used, otherwise as:

$$\hat{var}[\bar{x}_{t}]=\frac{\sum_{i=1}^{n_{t}}(x_{ti}-\bar{x}_{t})^2}{n_{t}(n_{t}-1)}$$

Stratified estimates of mean length will be calculated as follows, in which $N_t$ represents the abundance associated with sampling stratum $t$, $N$ represents the total abundance, and *L* represents the number of sampling strata:

$$\bar{x}=\frac{1}{N}\sum_{t=1}^L N_t\bar{x}_t$$

and

$$\hat{var}[\bar{x}]=\sum_{t=1}^L\left(\frac{N_t}{N}\right)^2 \hat{var}[\bar{x}_t]$$

\pagebreak

### If abundance is estimated with error

#### If there are proportions

The proportion of each age, sex, and/or length category *z* will be estimated for each sampling stratum *t* as follows:

$$\hat{p}_{tz}=\frac{n_{tz}}{n_t}$$

in which $n_{tz}$ equals the number of fish sampled during sampling stratum $t$ classified as age, sex, and/or length category $z$, and $n_t$ equals the number of fish sampled for age, sex, and/or length determination within sampling stratum $t$.

The sampling variance of $\hat{p}_{tz}$ will be estimated as the following (Cochran 1977) in which $\hat{N}_t$ is the estimated abundance of fish in sampling stratum $t$:

$$\hat{var}[\hat{p}_{tz}]=\frac{\hat{p}_{tz}(1-\hat{p}_{tz})}{n_t-1}\left(\frac{\hat{N}_t-n_t}{\hat{N}_t-1}\right)$$

if the finite population correction factor (FPC) is used; otherwise, as the following:

$$\hat{var}[\hat{p}_{tz}]=\frac{\hat{p}_{tz}(1-\hat{p}_{tz})}{n_t-1}$$

The total abundance by age, sex, and/or length category in each sampling stratum will be estimated as follows:

$$\hat{N}_{tz}=\hat{N}_t\hat{p}_{tz}$$

with variance estimated as (Goodman 1960):

$$\hat{var}[\hat{N}_{tz}]=\hat{N}_t^2\hat{var}[\hat{p}_{tz}] + \hat{p}_{tz}^2\hat{var}[\hat{N}_t]-\hat{var}[\hat{p}_{tz}]\hat{var}[\hat{p}_{tz}]$$

The total abundance by age, sex, and/or length category $z$ and its variance will then be estimated by summation as follows:

$$\hat{N}_z=\sum_{t=1}^{L}\hat{N}_{tz}$$

and

$$\hat{var}[\hat{N}_{z}]=\sum_{t=1}^{L}\hat{var}[\hat{N}_{tz}]$$

where $L$ equals the number of sampling strata.

Finally, the overall proportion by age, sex, and/or length category and its variance will be estimated as follows:

$$\hat{p}_z=\frac{\hat{N}_z}{\sum_{t=1}^{L}\hat{N}_t}$$

with variance estimated by the delta method (Casella & Berger 2002) as:

$$\hat{var}[\hat{p}_z] \approx \left(\frac{\hat{N}_z}{\sum_{t=1}^{L}\hat{N}_t}\right)^2\left(\frac{\hat{var}[\hat{N}_z]}{\hat{N}_z^2} + \frac{\sum_{t=1}^{L}\hat{var}[\hat{N}_t]}{(\sum_{t=1}^{L}\hat{N}_t)^2} - 2\frac{\hat{cov}[\hat{N}_z,\sum_{t=1}^{L}\hat{N}_t]}{\hat{N}_z\sum_{t=1}^{L}\hat{N}_t}\right)$$

in which

$$\hat{cov}[\hat{N}_z,\sum_{t=1}^{L}\hat{N}_t]=\sum_{t=1}^{L}\hat{p}_{tz}\hat{var}[\hat{N_t}]$$

The mean length by age, sex, and/or length for each sampling stratum will be estimated as follows:

$$\bar{x}_{tz}=\frac{\sum_{i=1}^{n_{tz}}x_{tzi}}{n_{tz}}$$

where $x_{tzi}$ is the length of the *i*th fish sampled of age, sex, and/or length $z$ during sampling stratum $t$.

The sampling variance of $\bar{x}_{tz}$ will be estimated as

$$\hat{var}[\bar{x}_{tz}]=\frac{\sum_{i=1}^{n_{tz}}(x_{tzi}-\bar{x}_{tz})^2}{n_{tz}(n_{tz}-1)}\left(\frac{\hat{N}_{tz}-n_{tz}}{\hat{N}_{tz}-1}\right)$$

if the finite population correction factor (FPC) is used; otherwise, as

$$\hat{var}[\bar{x}_{tz}]=\frac{\sum_{i=1}^{n_{tz}}(x_{tzi}-\bar{x}_{tz})^2}{n_{tz}(n_{tz}-1)}$$

The mean length by age, sex, and/or length category will then be estimated as follows:

$$\bar{x}_z=\sum_{t=1}^{L}\frac{\hat{N}_{tz}}{\hat{N}_z}\bar{x}_{tz}$$

with its variance approximated using a Taylor's series expansion (Mood et al. 1974):

$$\hat{var}[\bar{x}_z]\approx\sum_{t=1}^{L}\frac{\hat{N}_{tz}^2}{\hat{N}_z^2}\hat{var}[\bar{x}_{tz}]+\sum_{t=1}^{L}\frac{\left(\bar{x}_{tz}\hat{N}_z-\left(\sum_{u=1}^{L}\bar{x}_{uz}\hat{N}_{uz}\right)\right)^2}{\hat{N}_z^4}\hat{var}[\hat{N}_{tz}]$$

#### If there are no proportions to estimate

The mean length for each sampling stratum will be estimated as follows, where $x_{ti}$ is the length of the *i*th fish sampled within sampling stratum $t$, and $n_t$ is the number of fish in stratum *t* sampled for length:

$$\bar{x}_{t}=\frac{\sum_{i=1}^{n_{t}}x_{ti}}{n_{t}}$$

The sampling variance of $\bar{x}_{t}$ will be estimated as

$$\hat{var}[\bar{x}_{t}]=\frac{\sum_{i=1}^{n_{t}}(x_{ti}-\bar{x}_{t})^2}{n_{t}(n_{t}-1)}\left(\frac{\hat{N}_{t}-n_{t}}{\hat{N}_{t}-1}\right)$$

if the finite population correction factor (FPC) is used, otherwise as:

$$\hat{var}[\bar{x}_{t}]=\frac{\sum_{i=1}^{n_{t}}(x_{ti}-\bar{x}_{t})^2}{n_{t}(n_{t}-1)}$$

Stratified estimates of mean length will be calculated as follows, in which $\hat{N}_t$ and $\bar{x}_t$ represent the estimated abundance and mean length associated with stratum *t*, respectively:

$$\bar{x}=\frac{\sum_{t=1}^L \hat{N}_t\bar{x}_t}{\sum_{t=1}^L \hat{N}_t}$$

and

$$\hat{var}[\bar{x}] \approx \left(\frac{\sum_{t=1}^L \hat{N}_t\bar{x}_t}{\sum_{t=1}^L \hat{N}_t}\right)^2\left(\frac{\hat{var}[\sum_{t=1}^L \hat{N}_t\bar{x}_t]}{\left(\sum_{t=1}^L \hat{N}_t\bar{x}_t\right)^2}+\frac{\sum_{t=1}^L \hat{var}[\hat{N}_t]}{\left(\sum_{t=1}^L \hat{N}_t\right)^2}-2\frac{\hat{cov}[\sum_{t=1}^L \hat{N}_t,\sum_{t=1}^L N_t\bar{x}_t]}{\left(\sum_{t=1}^L \hat{N}_t\right)\left(\sum_{t=1}^L \hat{N}_t\bar{x}_t\right)}\right)$$

in which

$$\hat{cov}[\sum_{t=1}^L \hat{N}_t,\sum_{t=1}^L \hat{N}_t\bar{x}_t]=\sum_{t=1}^L \bar{x}_t\hat{var}[\hat{N}_t]$$

and

$$\hat{var}[\sum_{t=1}^L \hat{N}_t\bar{x}_t]=\sum_{t=1}^L\hat{N}_t^2\hat{var}[\bar{x}_t] + \bar{x}_t^2\hat{var}[\hat{N}_t]-\hat{var}[\hat{N}_t]\hat{var}[\bar{x}_t]$$

by means of the delta method (Casella & Berger 2002) and Goodman (1960), respectively.

\pagebreak

### If abundance is unknown and sample weights are used

#### If there are proportions

The proportion of each age, sex, and/or length category *z* will be estimated for each sampling stratum *t* as follows:

$$\hat{p}_{tz}=\frac{n_{tz}}{n_t}$$

in which $n_{tz}$ equals the number of fish sampled during sampling stratum $t$ classified as age, sex, and/or length category $z$, and $n_t$ equals the number of fish sampled for age, sex, and/or length determination within sampling stratum $t$.

The sampling variance of $\hat{p}_{tz}$ will be estimated as the following (Cochran 1977):

$$\hat{var}[\hat{p}_{tz}]=\frac{\hat{p}_{tz}(1-\hat{p}_{tz})}{n_t-1}$$

The overall proportion by age, sex, and/or length category and its variance will be estimated as follows, in which $w_t$ represents the sampling weight associated with stratum *t* and *L* equals the number of strata.  It is worth noting that weights $w_t$ are treated as constant (i.e. known without error), therefore all variance estimates must be interpreted as minima without further assumptions. 

$$\hat{p}_z=\frac{\sum_{t=1}^Lw_t\hat{p}_{tz}}{\sum_{t=1}^Lw_t}$$

and

$$\hat{var}[\hat{p}_z]=\frac{\sum_{t=1}^Lw_t^2\hat{var}[\hat{p}_{tz}]}{\left(\sum_{t=1}^Lw_t\right)^2}$$

The mean length by age, sex, and/or length for each sampling stratum will be estimated as follows:

$$\bar{x}_{tz}=\frac{\sum_{i=1}^{n_{tz}}x_{tzi}}{n_{tz}}$$

where $x_{tzi}$ is the length of the *i*th fish sampled of age, sex, and/or length $z$ during sampling stratum $t$.

The sampling variance of $\bar{x}_{tz}$ will be estimated as:

$$\hat{var}[\bar{x}_{tz}]=\frac{\sum_{i=1}^{n_{tz}}(x_{tzi}-\bar{x}_{tz})^2}{n_{tz}(n_{tz}-1)}$$

The mean length by age, sex, and/or length category will then be estimated as follows:

$$\bar{x}_z=\frac{\sum_{t=1}^{L}w_t\hat{p}_{tz}\bar{x}_{tz}}{\sum_{t=1}^{L}w_t\hat{p}_{tz}}$$

with its variance approximated using a Taylor's series expansion (Mood et al. 1974):

$$\hat{var}[\bar{x}_z]\approx\frac{\sum_{t=1}^{L}w_t\hat{p}_{tz}^2\hat{var}[\bar{x}_{tz}]}{\left(\sum_{t=1}^Lw_t\hat{p}_{tz}\right)^2}+\frac{\sum_{t=1}^{L}\left(\bar{x}_{tz}\sum_{u=1}^Lw_u\hat{p}_{uz}-\left(\sum_{u=1}^{L}\bar{x}_{uz}w_u\hat{p}_{uz}\right)\right)^2w_t^2\hat{var}[\hat{p}_{tz}]}{\left(\sum_{t=1}^Lw_t\hat{p}_{tz}\right)^4}$$

#### If there are no proportions to estimate

The mean length for each sampling stratum will be estimated as follows, where $x_{ti}$ is the length of the *i*th fish sampled within sampling stratum $t$, and $n_t$ is the number of fish in stratum *t* sampled for length:

$$\bar{x}_{t}=\frac{\sum_{i=1}^{n_{t}}x_{ti}}{n_{t}}$$

The sampling variance of $\bar{x}_{t}$ will be estimated as:

$$\hat{var}[\bar{x}_{t}]=\frac{\sum_{i=1}^{n_{t}}(x_{ti}-\bar{x}_{t})^2}{n_{t}(n_{t}-1)}$$

Stratified estimates of mean length will be calculated as follows, in which $w_t$ and $\bar{x}_t$ represent the sampling weight and average length associated with sampling stratum $t$, respectively.  It is worth noting that weights $w_t$ are treated as constant (i.e. known without error), therefore all variance estimates must be interpreted as minima without further assumptions. 

$$\bar{x}=\frac{\sum_{t=1}^L w_t\bar{x}_t}{\sum_{t=1}^L w_t}$$

and

$$\hat{var}[\bar{x}]=\frac{\sum_{t=1}^L w_t^2\hat{var}[\bar{x}_t]}{\left(\sum_{t=1}^L w_t\right)^2}$$

\pagebreak

## Pooled

### If abundance is known without error

#### If there are proportions

Proportions of each age, sex, and/or length category $z$ will be estimated as follows (Cochran 1977):

$$\hat{p}_z=\frac{n_z}{n}$$

and

$$\hat{var}[\hat{p}_z]=\frac{\hat{p}(1-\hat{p})}{n-1}\left(\frac{N-n}{N-1}\right)$$

if total abundance $N$ is known and the finite population correction factor (FPC) is used; otherwise as

$$\hat{var}[\hat{p}_z]=\frac{\hat{p}_z(1-\hat{p}_z)}{n-1}$$

in which $n_z$ denotes the number of fish sampled in age, sex, and/or length category $z$, $n$ denotes the total number of fish sampled, and *N* denotes the total abundance.

Total abundance for age, sex, and/or length category $z$ will be estimated as

$$\hat{N}_z=N\hat{p}_z$$ 

and

$$\hat{var}[\hat{N}_z]=N^2\hat{var}[\hat{p}_z]$$

The mean length associated with age, sex, and/or length category $z$ will be estimated as the following, in which $x_{zi}$ represents the length of the *i*th fish in age, sex, and/or length category *z* and $n_z$ represents the number of fish in age, sex, and/or length category *z* with an associated length measurement:

$$\bar{x}_z=\frac{\sum_{i=1}^{n_z}x_{zi}}{n_z}$$

and

$$\hat{var}[\bar{x}_z]=\frac{\sum_{i=1}^{n_z}(x_{zi}-\bar{x_z})^2}{n_z(n_z-1)}\left(\frac{\hat{N}_z-n_z}{\hat{N}_z-1}\right)$$

if the finite population correction factor (FPC) is used, otherwise as:

$$\hat{var}[\bar{x}_z]=\frac{\sum_{i=1}^{n_z}(x_{zi}-\bar{x_z})^2}{n_z(n_z-1)}$$

#### If there are no proportions to estimate

The mean length of all fish will be estimated as the following, in which $x_{i}$ represents the length of the *i*th fish, $n$ represents the number of fish with an associated length measurement, and *N* represents the total abundance:

$$\bar{x}=\frac{\sum_{i=1}^{n}x_{i}}{n}$$

and

$$\hat{var}[\bar{x}]=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n(n-1)}\left(\frac{N-n}{N-1}\right)$$

if the finite population correction factor (FPC) is used, otherwise as:

$$\hat{var}[\bar{x}]=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n(n-1)}$$



\pagebreak

### If abundance is estimated with error

#### If there are proportions

Proportions of each age, sex, and/or length category $z$ will be estimated as follows (Cochran 1977):

$$\hat{p}_z=\frac{n_z}{n}$$

and

$$\hat{var}[\hat{p}]=\frac{\hat{p}(1-\hat{p})}{n-1}\left(\frac{\hat{N}-n}{\hat{N}-1}\right)$$

if the finite population correction factor (FPC) is used, otherwise as

$$\hat{var}[\hat{p}]=\frac{\hat{p}(1-\hat{p})}{n-1}$$
in which $n_z$ denotes the number of fish sampled in age, sex, and/or length category $z$, $n$ denotes the total number of fish sampled, and $\hat{N}$ denotes the estimated abundance.

Total abundance for age, sex, and/or length category $z$ will be estimated as follows (Goodman 1960):

$$\hat{N}_z=\hat{N}\hat{p}_z$$

and

$$\hat{var}[\hat{N}_z]=\hat{N}^2\hat{var}[\hat{p}_z] + \hat{p}_z^2\hat{var}[\hat{N}]-\hat{var}[\hat{N}]\hat{var}[\hat{p}_z]$$

The mean length associated with age, sex, and/or length category $z$ will be estimated as the following, in which $x_{zi}$ represents the length of fish *i* within age, sex, and/or length category category *z*, and $n_z$ denotes the number of fish within age, sex, and/or length category *z* with an associated length measurement:

$$\bar{x}_z=\frac{\sum_{i=1}^{n_z}x_{zi}}{n_z}$$

and

$$\hat{var}[\bar{x}_z]=\frac{\sum_{i=1}^{n_z}(x_{zi}-\bar{x_z})^2}{n_z(n_z-1)}\left(\frac{\hat{N}_z-n_z}{\hat{N}_z-1}\right)$$

if the finite population correction factor (FPC) is used; otherwise as

$$\hat{var}[\bar{x}_z]=\frac{\sum_{i=1}^{n_z}(x_{zi}-\bar{x_z})^2}{n_z(n_z-1)}$$

#### If there are no proportions to estimate

The mean length of all fish will be estimated as the following, in which $x_{i}$ represents the length of the *i*th fish, $n$ represents the number of fish with an associated length measurement, and $\hat{N}$ represents the estimated total abundance:

$$\bar{x}=\frac{\sum_{i=1}^{n}x_{i}}{n}$$

and

$$\hat{var}[\bar{x}]=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n(n-1)}\left(\frac{\hat{N}-n}{\hat{N}-1}\right)$$

if the finite population correction factor (FPC) is used, otherwise as:

$$\hat{var}[\bar{x}]=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n(n-1)}$$

\pagebreak

### If abundance is unknown

#### If there are proportions

Proportions of each age, sex, and/or length category $z$ will be estimated as follows (Cochran 1977):

$$\hat{p}_z=\frac{n_z}{n}$$

and

$$\hat{var}[\hat{p}_z]=\frac{\hat{p}_z(1-\hat{p}_z)}{n-1}$$

in which $n_z$ denotes the number of fish sampled in age, sex, and/or length category $z$, and $n$ denotes the total number of fish sampled.

The mean length associated with age, sex, and/or length category $z$ will be estimated as the following, in which $x_{zi}$ denotes the length measurement associated with the *i*th fish in age, sex, and/or length category *z*:

$$\bar{x}_z=\frac{\sum_{i=1}^{n_z}x_{zi}}{n_z}$$

and

$$\hat{var}[\bar{x}_z]=\frac{\sum_{i=1}^{n_z}(x_{zi}-\bar{x_z})^2}{n_z(n_z-1)}$$

#### If there are no proportions to estimate

The mean length will be estimated as the following, in which $x_{i}$ denotes the length measurement associated with the *i*th fish and $n$ denotes the number of fish with an associated length measurement:

$$\bar{x}=\frac{\sum_{i=1}^{n}x_{i}}{n}$$

and

$$\hat{var}[\bar{x}]=\frac{\sum_{i=1}^{n}(x_{i}-\bar{x})^2}{n(n-1)}$$

## References

Casella, George and Roger L. Berger. 2002. *Statistical Inference*. Australia ; Pacific Grove, CA, Thomson Learning

Cochran, W. G.  1977.  *Sampling techniques*. 3rd edition.  John Wiley and Sons, New York.

Goodman, L.A., 1960. On the exact variance of products. *Journal of the American statistical association, 55*(292), pp.708-713.

Mood, A. M., F. A. Graybill, and D. C. Boes.  1974.  *Introduction to the theory of statistics*. 3rd edition.  McGraw-Hill Book Co., New York.
 
```{r, results='asis', echo=FALSE}
print(citation(), style="text")
cat("\n")
print(citation("dsftools"), style="text")
cat("\n")
print(citation("knitr"), style="text")
```
